<?php

namespace Database\Factories;

use App\Models\RecyclingBin;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\RecyclingBin>
 */
class RecyclingBinFactory extends Factory
{
    protected $model = RecyclingBin::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->company() . ' Recycling Bin',
            'latitude' => fake()->latitude(),
            'longitude' => fake()->longitude(),
            // qr_key is auto-generated by model's booted() method
        ];
    }

    /**
     * Create a bin at specific coordinates.
     */
    public function atLocation(float $latitude, float $longitude): static
    {
        return $this->state(fn(array $attributes) => [
            'latitude' => $latitude,
            'longitude' => $longitude,
        ]);
    }
}
