<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\RecyclingBin;

class RecyclingBinController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return response()->json(RecyclingBin::all(), 200);
    }

    /**
     * Store a newly created resource in storage (Admin only).
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
        ]);

        // Key is auto-generated by model event
        $bin = RecyclingBin::create($validated);

        return response()->json($bin, 201);
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $bin = RecyclingBin::find($id);

        if (! $bin) {
            return response()->json(['message' => 'Bin not found.'], 404);
        }

        return response()->json($bin, 200);
    }

    /**
     * Update the specified resource in storage (Admin only).
     */
    public function update(Request $request, $id)
    {
        $bin = RecyclingBin::find($id);

        if (! $bin) {
            return response()->json(['message' => 'Bin not found.'], 404);
        }

        $validated = $request->validate([
            'name' => 'sometimes|string|max:255',
            'latitude' => 'sometimes|numeric',
            'longitude' => 'sometimes|numeric',
        ]);

        $bin->update($validated);

        return response()->json($bin, 200);
    }

    /**
     * Remove the specified resource from storage (Admin only).
     */
    public function destroy($id)
    {
        $bin = RecyclingBin::find($id);

        if (! $bin) {
            return response()->json(['message' => 'Bin not found.'], 404);
        }

        $bin->delete();

        return response()->json(['message' => 'Bin deleted successfully.'], 200);
    }
}
